name: ReviewDog
on:
  pull_request:

jobs:
  limit-changes:
    uses: ./.github/workflows/limit_changed_lines.yml
    with:
      limit: 100
      extension: kt|yml
      exclude_dir: .github

  review-dog:
    runs-on: ubuntu-latest
    needs: [ limit-changes ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Spotless
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessKotlinApply

      - name: ReviewDog
        uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: spotless
