name: ReviewDog
on: [pull_request]
jobs:
  count-diff-lines:
    name: Count lines
    runs-on: ubuntu-latest

    env:
      BASE: ${{ github.base_ref }}
      HEAD: ${{ github.head_ref }}

    steps:
      - name: Checkout base
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BASE }}
          fetch-depth: 0

      - name: diff
        run: |
          git branch --show-current
          git diff ${{ env.HEAD }} ${{ env.BASE }} --numstat | grep ".*\.kt$" | awk '{additions+=$1} END {printf "lines=%d\n", additions}' >> $GITHUB_ENV
      - name: check
        run: echo ${{ env.lines }}

  kotlin:
    name: runner / suggester / spotless
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Checkout ref
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Spotless
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessKotlinApply

      - name: ReviewDog
        uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: spotless

  echo:
    name: Echo secret
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.APP_TOKEN }}
